-- SELECT COUNT (*) FROM invoice
-- WHERE billing_country LIKE '%USA%'

-- SELECT MAX(total) FROM invoice
-- WHERE total IS NOT NULL
-- SELECT MIN(total) FROM invoice
-- WHERE total IS NOT NULL
-- SELECT (total<5) FROM invoice
-- WHERE total IS NOT NULL
-- SELECT COUNT (*) FROM invoice
-- WHERE total <5
-- SELECT COUNT (*) FROM invoice
-- WHERE total >5
-- SELECT COUNT (*) FROM invoice
-- WHERE billing_state IN ('CA', 'TX', 'AZ')
-- SELECT AVG(total) FROM invoice
-- SELECT SUM(total) FROM invoice
-- UPDATE invoice
-- SET total = 24
-- WHERE invoice_id = 5
-- DELETE FROM invoice 
-- WHERE invoice_id = 1